name: unique_device_id
description: Get unique device id
version: 0.0.2
publish_to: https://pub.dartlang.org
repository: https://github.com/jukqaz/flutter_unique_device_id

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jukqaz.unique_device_id
        pluginClass: UniqueDeviceIdPlugin
      ios:
        pluginClass: UniqueDeviceIdPlugin
